// ============================================================
// ielts.js — Kho ĐỀ IELTS (Writing Task 2 + Speaking) cố định, miễn phí, không cần API.
// Chỉ là ĐỀ BÀI (không vi phạm bản quyền). Xoay theo ngày -> mỗi ngày một đề.
// (Chấm bài & sinh đề Đọc dùng API OpenAI — tùy chọn.)
// ============================================================

const IELTS_DAILY = [
  { theme: "Education",
    writing: "Some people believe that university education should be free for all students, while others think students should pay for it themselves. Discuss both views and give your own opinion.",
    cue: "Describe a subject you enjoyed studying at school.",
    bullets: ["what the subject was", "when and where you studied it", "what you learned", "and explain why you enjoyed it"],
    part3: ["Should schools focus more on academic or practical skills?", "How has education changed compared to the past?", "Do you think online learning will replace traditional classrooms?"] },
  { theme: "Environment",
    writing: "Many people argue that individual efforts to protect the environment are pointless and that only governments and large companies can make a real difference. To what extent do you agree or disagree?",
    cue: "Describe an environmental problem in your area.",
    bullets: ["what the problem is", "what causes it", "how it affects people", "and explain what could be done about it"],
    part3: ["Whose responsibility is it to protect the environment?", "How can we encourage people to recycle more?", "Do you think electric cars are the solution to pollution?"] },
  { theme: "Technology",
    writing: "Some people think that modern technology is making people less sociable. To what extent do you agree or disagree?",
    cue: "Describe a piece of technology you find useful.",
    bullets: ["what it is", "how often you use it", "what you use it for", "and explain why it is useful to you"],
    part3: ["Has technology improved the way we communicate?", "What are the disadvantages of relying too much on technology?", "Will artificial intelligence create or destroy jobs?"] },
  { theme: "Work",
    writing: "Nowadays many people change their career and place of work several times during their lives. Is this a positive or negative development?",
    cue: "Describe a job you would like to do in the future.",
    bullets: ["what the job is", "what skills it requires", "why you are interested in it", "and explain how you could prepare for it"],
    part3: ["Is work-life balance important?", "Why do some people prefer working from home?", "Should companies offer lifelong employment?"] },
  { theme: "Health",
    writing: "In some countries the number of overweight people is increasing. What do you think are the causes of this, and what solutions can you suggest?",
    cue: "Describe a healthy habit you have.",
    bullets: ["what the habit is", "when you started it", "how you keep it up", "and explain how it benefits you"],
    part3: ["Whose responsibility is public health — the individual or the government?", "Why do people eat unhealthy food despite knowing the risks?", "How can cities encourage people to be more active?"] },
  { theme: "Society",
    writing: "Some people believe that the gap between the rich and the poor is widening. What problems does this cause, and what measures could reduce the gap?",
    cue: "Describe a person in your community you admire.",
    bullets: ["who the person is", "what they do", "how you know about them", "and explain why you admire them"],
    part3: ["Should wealthy people pay higher taxes?", "How can communities help disadvantaged groups?", "Is money the main measure of success?"] },
  { theme: "Media",
    writing: "News organisations should report only positive stories rather than negative events. To what extent do you agree or disagree?",
    cue: "Describe a piece of news you recently read or heard.",
    bullets: ["what it was about", "where you saw it", "how you felt about it", "and explain why it was memorable"],
    part3: ["Can we trust the news we read online?", "How has social media changed the way we get news?", "Should there be limits on what the media can report?"] },
  { theme: "Travel & Tourism",
    writing: "International tourism has brought enormous benefits to many places, but it can also cause problems. Do the advantages outweigh the disadvantages?",
    cue: "Describe a place you would like to visit.",
    bullets: ["where it is", "how you know about it", "what you would do there", "and explain why you want to visit it"],
    part3: ["Why do people enjoy travelling abroad?", "What impact does tourism have on local cultures?", "Is travelling still valuable in the age of virtual reality?"] },
  { theme: "Family & Children",
    writing: "Some people think children should be given more freedom, while others believe strict discipline leads to better behaviour. Discuss both views and give your opinion.",
    cue: "Describe a skill you learned from a family member.",
    bullets: ["what the skill is", "who taught you", "how you learned it", "and explain how it is useful now"],
    part3: ["What is the ideal age for children to become independent?", "How has the role of parents changed?", "Should grandparents help raise children?"] },
  { theme: "Culture & Art",
    writing: "Some people believe that governments should spend money preserving old buildings, while others think this money should be used to build new housing. Discuss both views and give your opinion.",
    cue: "Describe a traditional festival in your country.",
    bullets: ["what the festival is", "when it takes place", "what people do", "and explain why it is important"],
    part3: ["Why is it important to preserve cultural traditions?", "Should the government fund the arts?", "Is globalisation a threat to local cultures?"] },
  { theme: "Cities & Housing",
    writing: "More and more people are moving to large cities. What are the causes of this trend, and what problems can it create?",
    cue: "Describe an area of your city you like.",
    bullets: ["where it is", "what it looks like", "what people do there", "and explain why you like it"],
    part3: ["What makes a city a good place to live?", "How can governments solve traffic congestion?", "Will people prefer to live in cities or the countryside in the future?"] },
  { theme: "Language",
    writing: "Some people think that everyone should learn English, while others believe it threatens local languages. Discuss both views and give your own opinion.",
    cue: "Describe a language you would like to learn.",
    bullets: ["which language it is", "why you want to learn it", "how you would learn it", "and explain how it could help you"],
    part3: ["Why do some languages disappear?", "Is it better to learn a language in childhood?", "Will technology make language learning unnecessary?"] },
  { theme: "Crime & Law",
    writing: "Some people believe that the best way to reduce crime is to give longer prison sentences. Others think there are better alternatives. Discuss both views and give your opinion.",
    cue: "Describe a rule at school or work that you think is important.",
    bullets: ["what the rule is", "why it exists", "what happens if it is broken", "and explain why you think it is important"],
    part3: ["What causes people to commit crimes?", "Do you think punishment or rehabilitation works better?", "Should communities be involved in preventing crime?"] },
  { theme: "Money & Consumerism",
    writing: "Many people today spend more money than they earn and rely on credit. What are the causes of this, and what effects does it have on individuals and society?",
    cue: "Describe something you bought that you were happy with.",
    bullets: ["what it was", "why you bought it", "how much it cost", "and explain why you were satisfied"],
    part3: ["Why do people buy things they do not need?", "Is advertising harmful?", "Should schools teach children how to manage money?"] },
  { theme: "Science & Space",
    writing: "Governments spend large amounts of money on space exploration. Some argue this money should be spent on solving problems on Earth. To what extent do you agree or disagree?",
    cue: "Describe a scientific discovery you find interesting.",
    bullets: ["what it is", "how you learned about it", "what it changed", "and explain why it interests you"],
    part3: ["Should governments fund scientific research?", "Are humans too dependent on science?", "What scientific problem is most urgent today?"] },
  { theme: "Sport & Leisure",
    writing: "Some people think that competitive sports teach children valuable lessons, while others believe they put too much pressure on them. Discuss both views and give your opinion.",
    cue: "Describe a sport or physical activity you enjoy.",
    bullets: ["what it is", "when you do it", "who you do it with", "and explain why you enjoy it"],
    part3: ["Why is it important for people to exercise?", "Should sport be compulsory in schools?", "Do professional athletes earn too much?"] },
  { theme: "Work & Automation",
    writing: "As machines and computers become more capable, many traditional jobs are disappearing. Is this a positive or negative development?",
    cue: "Describe a time you learned to use a new tool or device.",
    bullets: ["what it was", "why you needed it", "how you learned it", "and explain how it helped you"],
    part3: ["Which jobs are most at risk from automation?", "How should workers prepare for the future?", "Can machines ever fully replace humans?"] },
  { theme: "Globalisation",
    writing: "Global trade has made many products cheaper and more available, but it has also harmed local businesses. Do the benefits outweigh the drawbacks?",
    cue: "Describe a foreign product you often use.",
    bullets: ["what it is", "where it comes from", "how often you use it", "and explain why you prefer it"],
    part3: ["How has globalisation affected your country?", "Should governments protect local businesses?", "Is cultural identity being lost due to globalisation?"] },
];
