// ============================================================
// quizbank.js — Ngân hàng câu hỏi CỐ ĐỊNH (offline) cho "Học thụ động".
// GRAMMAR_BANK: ngữ pháp nền tảng. IELTS_BANK: câu hỏi kiểu IELTS (từ vựng/collocation/đọc hiểu nhanh).
// Mỗi câu: q (đề), o (lựa chọn), a (chỉ số đáp án đúng), e (giải thích).
// ============================================================

const GRAMMAR_BANK = [
  { q: "She ___ to the library every Saturday.", o: ["go", "goes", "going", "gone"], a: 1, e: "Hiện tại đơn, chủ ngữ số ít 'She' → thêm -es." },
  { q: "Look! The children ___ in the garden.", o: ["play", "plays", "are playing", "played"], a: 2, e: "'Look!' báo hiệu hành động đang diễn ra → hiện tại tiếp diễn." },
  { q: "I ___ in this city since 2018.", o: ["live", "lived", "have lived", "am living"], a: 2, e: "'since + mốc' → hiện tại hoàn thành." },
  { q: "They ___ dinner when the power went out.", o: ["had", "were having", "have had", "have"], a: 1, e: "Hành động đang diễn ra bị cắt ngang → quá khứ tiếp diễn." },
  { q: "By the time we arrived, the show ___.", o: ["started", "has started", "had started", "was starting"], a: 2, e: "Việc xảy ra TRƯỚC một mốc quá khứ → quá khứ hoàn thành." },
  { q: "If it ___ tomorrow, we will cancel the trip.", o: ["rain", "rains", "will rain", "rained"], a: 1, e: "Điều kiện loại 1: If + hiện tại đơn, will + V." },
  { q: "If I ___ you, I would accept the offer.", o: ["am", "was", "were", "be"], a: 2, e: "Điều kiện loại 2 dùng 'were' cho mọi ngôi." },
  { q: "If she had studied harder, she ___ the exam.", o: ["would pass", "would have passed", "passed", "will pass"], a: 1, e: "Điều kiện loại 3: would have + V3." },
  { q: "The report ___ by the team last week.", o: ["wrote", "was written", "is written", "has written"], a: 1, e: "Bị động quá khứ đơn: was/were + V3." },
  { q: "English ___ in many countries around the world.", o: ["speaks", "is speaking", "is spoken", "spoke"], a: 2, e: "Bị động hiện tại đơn: is/are + V3." },
  { q: "He said that he ___ tired.", o: ["is", "was", "will be", "has been"], a: 1, e: "Câu tường thuật: lùi thì, is → was." },
  { q: "She asked me where I ___.", o: ["live", "lived", "do live", "am living"], a: 1, e: "Tường thuật câu hỏi: lùi thì, trật tự khẳng định." },
  { q: "The man ___ lives next door is a doctor.", o: ["which", "who", "whom", "whose"], a: 1, e: "'who' thay cho người làm chủ ngữ." },
  { q: "This is the book ___ I told you about.", o: ["who", "which", "whose", "where"], a: 1, e: "'which' thay cho vật." },
  { q: "That's the student ___ project won the prize.", o: ["who", "which", "whose", "that"], a: 2, e: "'whose' chỉ sở hữu." },
  { q: "I enjoy ___ novels in my free time.", o: ["to read", "reading", "read", "readed"], a: 1, e: "'enjoy' luôn theo sau bởi V-ing." },
  { q: "She decided ___ abroad next year.", o: ["studying", "to study", "study", "studied"], a: 1, e: "'decide' theo sau bởi to + V." },
  { q: "He is good at ___ problems quickly.", o: ["solve", "to solve", "solving", "solved"], a: 2, e: "Sau giới từ 'at' dùng V-ing." },
  { q: "You ___ smoke here; it's a hospital.", o: ["mustn't", "don't have to", "shouldn't have", "needn't"], a: 0, e: "'mustn't' = cấm; 'don't have to' = không cần." },
  { q: "The lights are off. They ___ have gone out.", o: ["must", "should", "can", "would"], a: 0, e: "'must have + V3' = suy đoán chắc chắn về quá khứ." },
  { q: "You ___ see a doctor if the pain continues.", o: ["should", "must not", "could have", "would"], a: 0, e: "'should' đưa lời khuyên." },
  { q: "I bought ___ umbrella because it was raining.", o: ["a", "an", "the", "(no article)"], a: 1, e: "'umbrella' bắt đầu bằng âm nguyên âm /ʌ/ → dùng 'an'." },
  { q: "___ sun rises in the east.", o: ["A", "An", "The", "(no article)"], a: 2, e: "Vật duy nhất → 'the'." },
  { q: "___ is essential for all living things.", o: ["A water", "The water", "Water", "An water"], a: 2, e: "Danh từ không đếm được nghĩa chung → không mạo từ." },
  { q: "This building is ___ than the one next to it.", o: ["tall", "taller", "tallest", "more tall"], a: 1, e: "So sánh hơn với tính từ ngắn: -er." },
  { q: "It was ___ film I have ever seen.", o: ["the more interesting", "the most interesting", "most interesting", "more interesting"], a: 1, e: "So sánh nhất với tính từ dài: the most." },
  { q: "The more you practise, ___ you become.", o: ["the better", "better", "the best", "the good"], a: 0, e: "Cấu trúc 'the + comparative…, the + comparative…'." },
  { q: "___ the heavy rain, the match continued.", o: ["Although", "Despite", "Because", "So"], a: 1, e: "'Despite' + danh từ; 'Although' + mệnh đề." },
  { q: "___ he was exhausted, he finished the race.", o: ["Despite", "In spite of", "Although", "Because of"], a: 2, e: "'Although' + mệnh đề (S+V)." },
  { q: "The road was closed ___ the accident.", o: ["because", "because of", "although", "so that"], a: 1, e: "'because of' + danh từ." },
  { q: "Never ___ such a beautiful sunset.", o: ["I have seen", "have I seen", "I saw", "did I saw"], a: 1, e: "Đảo ngữ sau 'Never': have I seen." },
  { q: "Not only ___ the test, but he also got the highest score.", o: ["he passed", "did he pass", "he did pass", "passed he"], a: 1, e: "Đảo ngữ sau 'Not only'." },
  { q: "There isn't ___ milk left in the fridge.", o: ["many", "much", "a few", "few"], a: 1, e: "'milk' không đếm được → much." },
  { q: "She has ___ friends, so she often feels lonely.", o: ["few", "a few", "little", "a little"], a: 0, e: "'few' mang nghĩa phủ định: rất ít." },
  { q: "I need ___ advice about my studies.", o: ["an", "some", "a few", "many"], a: 1, e: "'advice' không đếm được → some advice." },
  { q: "I wish I ___ more time to travel.", o: ["have", "had", "will have", "having"], a: 1, e: "Wish ở hiện tại → quá khứ đơn." },
  { q: "I wish I ___ harder for the exam last year.", o: ["studied", "had studied", "study", "would study"], a: 1, e: "Wish tiếc nuối quá khứ → quá khứ hoàn thành." },
  { q: "It's time we ___ home.", o: ["go", "went", "will go", "going"], a: 1, e: "'It's time' + quá khứ đơn." },
  { q: "Neither the manager nor the employees ___ informed.", o: ["was", "were", "is", "has been"], a: 1, e: "Neither…nor: chia theo danh từ gần động từ nhất (employees)." },
  { q: "The number of applicants ___ increasing every year.", o: ["are", "is", "were", "have been"], a: 1, e: "'The number of' → động từ số ít." },
  { q: "A number of students ___ absent today.", o: ["is", "was", "are", "has been"], a: 2, e: "'A number of' + N số nhiều → động từ số nhiều." },
  { q: "Everyone in the class ___ done the homework.", o: ["have", "has", "are", "were"], a: 1, e: "'Everyone' là số ít." },
  { q: "The meeting ___ at 9 a.m. tomorrow (lịch cố định).", o: ["starts", "will start", "is starting", "started"], a: 0, e: "Lịch trình cố định dùng hiện tại đơn." },
  { q: "By 2030, scientists ___ a cure for this disease.", o: ["will find", "will have found", "found", "have found"], a: 1, e: "'By + mốc tương lai' → tương lai hoàn thành." },
  { q: "She is used to ___ early every morning.", o: ["wake", "wakes", "waking", "woke"], a: 2, e: "'be used to' + V-ing (đã quen với việc)." },
];

const IELTS_BANK = [
  { q: "Choose the best word: The government should ___ measures to reduce pollution.", o: ["take", "make", "do", "give"], a: 0, e: "Collocation: take measures." },
  { q: "Choose the best word: Education plays a crucial ___ in economic development.", o: ["part", "role", "act", "duty"], a: 1, e: "Collocation: play a crucial role in." },
  { q: "Choose the best word: This policy has a significant ___ on employment.", o: ["affect", "impact", "effort", "result"], a: 1, e: "Collocation: have an impact on." },
  { q: "Academic synonym of 'a lot of problems':", o: ["numerous issues", "many troubles", "lots of things", "big problems"], a: 0, e: "'numerous issues' trang trọng, hợp văn học thuật." },
  { q: "Best linking word: Renewable energy is clean; ___, it is still expensive.", o: ["moreover", "however", "therefore", "for example"], a: 1, e: "Câu sau tương phản với câu trước → however." },
  { q: "Best linking word: Traffic is heavy; ___, the city plans to expand the metro.", o: ["however", "therefore", "although", "whereas"], a: 1, e: "Quan hệ nguyên nhân → kết quả → therefore." },
  { q: "In Writing Task 2, the minimum word count is:", o: ["150 words", "200 words", "250 words", "300 words"], a: 2, e: "Task 2 tối thiểu 250 từ." },
  { q: "In Writing Task 1 (Academic), you should NOT:", o: ["give an overview", "compare data", "give your personal opinion", "group information"], a: 2, e: "Task 1 mô tả khách quan, không nêu ý kiến cá nhân." },
  { q: "In Reading, 'Not Given' means:", o: ["the text contradicts it", "the text does not mention it", "it is false", "it is partly true"], a: 1, e: "Not Given = bài đọc không đề cập." },
  { q: "In Speaking Part 2, you have ___ to prepare.", o: ["30 seconds", "1 minute", "2 minutes", "no time"], a: 1, e: "Part 2: 1 phút chuẩn bị, nói 1–2 phút." },
  { q: "Choose the more academic phrase:", o: ["kids these days", "young people nowadays", "guys today", "youngsters now"], a: 1, e: "'young people nowadays' trang trọng, phù hợp bài viết." },
  { q: "Choose the best word: Many countries are facing a ___ shortage of skilled workers.", o: ["strong", "severe", "big", "hard"], a: 1, e: "Collocation: a severe shortage." },
  { q: "Choose the best word: The findings ___ that exercise improves memory.", o: ["speak", "tell", "suggest", "say"], a: 2, e: "Văn học thuật: findings suggest/indicate." },
  { q: "Which sentence is grammatically correct?", o: ["Despite of the rain, we went out.", "Despite the rain, we went out.", "Despite it rained, we went out.", "Despite that rain, we went."], a: 1, e: "'Despite' + danh từ, không có 'of'." },
  { q: "Which sentence is grammatically correct?", o: ["There are less cars than before.", "There are fewer cars than before.", "There is fewer cars.", "There are little cars."], a: 1, e: "'fewer' cho danh từ đếm được." },
  { q: "Best paraphrase of 'The number of tourists rose sharply':", o: ["Tourists went up a bit", "There was a sharp increase in tourist numbers", "Tourists were sharp", "The tourists rise sharp"], a: 1, e: "Danh từ hóa: a sharp increase in…" },
  { q: "Choose the best word: Governments must ___ the gap between rich and poor.", o: ["narrow", "short", "small", "low"], a: 0, e: "Collocation: narrow the gap." },
  { q: "Choose the best word: Air pollution is largely ___ to vehicle emissions.", o: ["because", "due", "caused", "attributed"], a: 3, e: "Collocation: be attributed to." },
  { q: "In Listening, if the answer limit is 'NO MORE THAN TWO WORDS', writing three words will be:", o: ["accepted", "marked wrong", "half correct", "ignored"], a: 1, e: "Vượt giới hạn từ → sai." },
  { q: "Choose the best conclusion opener for Task 2:", o: ["So that's all", "In conclusion", "By the way", "Anyway"], a: 1, e: "'In conclusion' trang trọng, chuẩn học thuật." },
];
